### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by zalexstudios** [Cyboulette/MyGuestHouse#1]
Hello!
I geting your script and install... 
But it's French! 
Please ! If you have English version send me to zalexstudiso@gmail.com
Thank you!

**Comment by zalexstudios** [comment]
Have you the real need to use this project ? Yes !
i want to do "Rent of apartment per night" servise.
midification a litle bit.
Missing folder for upload images "slides" --- Added!

Will be thanksfully for your help!

**Comment by Cyboulette** [comment]
The application doesn't have any payment system.

I'm not sure this application is perfect for you need. But if you think is corresponding to your needs, and you want absolutely this app, I can translate it. 

But first, install it, and check it fill your needs.

**Comment by zalexstudios** [comment]
Install allready!
vv.bocrbr.u
Please! If not to difficult for you to translate it!
What dose it mean 2 icon "Une chambre ..." and "... des prestations" ? For what?
Tnak you!

**Comment by zalexstudios** [comment]
Sorry!
vv.bocrbr.ru
